name: Turn-N-Burn Admin Panel Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.9.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0

    - name: Installing dependencies
      run: npm install

    - name: Set up environment variables
      env:
        NEXT_PUBLIC_BASE_URL_SERVER: ${{ vars.NEXT_PUBLIC_BASE_URL_SERVER }}
      run: |
        echo "NEXT_PUBLIC_BASE_URL_SERVER=$NEXT_PUBLIC_BASE_URL_SERVER" >> $GITHUB_ENV
    
    - name: Build
      run: npm run build

    - name: Stop previous PM2 instance (if running)
      run: |
        pm2 stop turn-n-burn-admin || true
        pm2 delete turn-n-burn-admin || true
      continue-on-error: true

    - name: Starting Application with PM2
      id: start_pm2
      run: |
        pm2 start npm --name "turn-n-burn-admin" -- run start -- -p 3000
      continue-on-error: true

    - name: Print IP if application started successfully
      if: ${{ steps.start_pm2.outcome == 'success' }}
      run: |
        RUNNER_IP=$(curl -s http://checkip.amazonaws.com)
        echo "App is running on IP address: http://$RUNNER_IP:3000"
      
    # - name: Show PM2 logs
    #   run: |
    #     npx pm2 logs turn-n-burn-admin --lines 100
